builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    gomips:
      - softfloat
      - hardfloat

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Mips }}_{{ .Mips }}{{ end }}"